### ISSUE TITLE
Default values in structs?

### ISSUE THREAD

**Issue by akaDuality** [apple/pkl-swift#20]
I would like to generate an analytics event like this:
```swift
struct LoginEvent {
    let name: String = "Login"
}
```

But the only way I have found is that I can create a template and evaluate values from a file. Pkl example:
```javascript
module LoginEvent

name = "Login"
```

The result is fully mutable and lost default values: 
```swift
struct LoginEvent {
    var name: String
}
```

Is there any way to provide a default value during code generation and make `let` properties?

**Comment by stackoverflow** [comment]
The generator will not generate data, so it can't generate default values. Doing so would require a 1-to-1 Pkl -> Swift code translator:

```pkl
class Foo {
  myProperty = complicatedFunction() // <- how to translate `complicateFunction` from Pkl to Swift?
}
```

You can use the auto-generated `loadFrom` function to load data from Pkl.
