### ISSUE TITLE
Sendable compliance for code generated types

### ISSUE THREAD

**Issue by abidon** [apple/pkl-swift#22]
Making code generated types `Sendable` (when possible) would be nice in anticipation of Swift 6.

There's also those warnings about `registeredIdentifier` not being concurrency-safe. Is there any particular reason why this property is not a `let` constant ?

```diff
public struct Module: PklRegisteredType, Decodable, Hashable {
-    public static var registeredIdentifier: String = "Foo"
+    public static let registeredIdentifier: String = "Foo"

    // ...
}
```

**Comment by bioball** [comment]
We'll do a release soon!

**Comment by bioball** [comment]
0.3.0 is released!

**Comment by ehmurray8** [comment]
The new version works for me, thank you!
